services:
  postgres:
    image: postgres
    container_name: binspire-database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend

  redis:
    image: redis
    container_name: binspire-redis
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    networks:
      - backend

networks:
  backend:
